/**
 * Represents an ArcGIS Server service item returned from directory.
 */
interface IService {
  name: string;
  type: string;
}

/**
 * Link information generated by this application
 */
interface ILinkInfo {
  name: string;
  url: string;
}

/**
 * Information about a service
 */
interface IServerInfo {
  [key: string]: any;
  currentVersion?: number;
  folders?: ILinkInfo[];
  services?: ILinkInfo[];
}
