/**
 * Represents an ArcGIS Server service item returned from directory.
 */
export interface IService {
  name: string;
  type: string;
}

/**
 * Link information generated by this application
 */
export interface ILinkInfo {
  name: string;
  url: string;
}

/**
 * Information about a service
 */
export interface IServerInfo extends Record<string, unknown> {
  currentVersion?: number;
  folders?: ILinkInfo[];
  services?: ILinkInfo[];
}

export interface IGeoTransform {
  wkid: number;
  latestWkid: number;
  transformForward: boolean;
  name: string;
}

export interface IDatumTransformation {
  geoTransforms: IGeoTransform[];
}
